- name: Remove the old Docker packages
  ansible.builtin.dnf:
    name:
      [
        "docker",
        "docker-client",
        "docker-client-latest",
        "docker-common",
        "docker-latest",
        "docker-latest-logrotate",
        "docker-logrotate",
        "docker-selinux",
        "docker-engine-selinux",
        "docker-engine",
      ]
    state: absent
  tags:
    - docker

- name: Installing DNF Plugin Core
  dnf:
    name: dnf-plugins-core
  tags:
    - docker

- name: install docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  tags:
    - docker

- name: Installing Docker
  ansible.builtin.dnf:
    name:
      [
        "docker-ce",
        "docker-ce-cli",
        "containerd.io",
        "docker-buildx-plugin",
        "docker-compose-plugin",
      ]
  tags:
    - docker

- name: Start Docker daemon 
  ansible.builtin.systemd:
    state: started
    name: docker
  tags:
    - docker

- name: Enable Docker daemon 
  systemd:
    name: docker
    enabled: yes
    masked: no
  tags:
    - docker

- name: Add the user to docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    group: docker
  tags:
    - docker