- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/Alkiviadroot/.dotfiles.git'
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    version: main
  tags:
    - dotfiles
